# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev

version: "3"

shopt:
  - expand_aliases

vars:
  TARGET: x86_64-pc-windows-gnu

  LOCAL_BUILD_DIR: .build

  GVSBUILD_DIR: "C:/.tmp/gvs"
  GVSBUILD_DIR_LNK: "{{.LOCAL_BUILD_DIR}}/gvsbuild"

  GTK_DIR: "{{ joinPath .TASKFILE_DIR .GVSBUILD_DIR_LNK }}"

  GVS_GTK_ROOT_DIR: "{{.GVSBUILD_DIR}}/gtk/x64/release"

  RUN_WINDOWS: "cmd /d /c"
  RUN_UNIX: "sh -c"
  RUN: '{{if eq OS "windows"}}{{.RUN_WINDOWS}}{{ else }}{{.RUN_UNIX}}{{ end }}'

  BUILD_TOOLCHAIN:
  BUILD_ARCH: x86_64
  BUILD_CC: clang
  PACKAGE_PARTS:
    - "mingw-w64"
    - "{{.BUILD_TOOLCHAIN}}"
    - "{{.BUILD_ARCH}}"
  PACKAGE_NAME_PREFIX: '{{ without .PACKAGE_PARTS "" | join "-" }}'
  MSYS2_PACKAGES:
    - "git"
    - "ncurses"
    - "{{.PACKAGE_NAME_PREFIX}}-{{.BUILD_CC}}"
    - "{{.PACKAGE_NAME_PREFIX}}-clang"
    - "{{.PACKAGE_NAME_PREFIX}}-ncurses"
    - "{{.PACKAGE_NAME_PREFIX}}-ntldd"
    - "{{.PACKAGE_NAME_PREFIX}}-openssl"
    - "{{.PACKAGE_NAME_PREFIX}}-pkgconf"
    - "{{.PACKAGE_NAME_PREFIX}}-zlib"
    - "{{.PACKAGE_NAME_PREFIX}}-gstreamer"
    - "{{.PACKAGE_NAME_PREFIX}}-pango"
    - "{{.PACKAGE_NAME_PREFIX}}-gcc"
    - "{{.PACKAGE_NAME_PREFIX}}-binutils"
    - "{{.PACKAGE_NAME_PREFIX}}-cairo"
    - "{{.PACKAGE_NAME_PREFIX}}-gdk-pixbuf2"
    - "{{.PACKAGE_NAME_PREFIX}}-glib2"
    - "{{.PACKAGE_NAME_PREFIX}}-libepoxy"
    - "{{.PACKAGE_NAME_PREFIX}}-pango"
    - "{{.PACKAGE_NAME_PREFIX}}-cairo"

env:
  VCPKG_DISABLE_METRICS: 1

  # PATH variable with GTK bin folder added. Not able to override
  # the PATH variable globally here so we do it locally as needed.
  PATH_GTK: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "bin" }}{{ if eq OS "windows" }};{{ else }}:{{ end }}{{ env "PATH" }}'

  GTK_ROOT_DIR: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "" }}'
  GDK_PIXBUF_MODULE_FILE: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" }}'
  GIO_EXTRA_MODULES: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "lib/gio/modules" }}'
  GTK_DATA_PREFIX: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "share" }}'
  GTK_PATH: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "share/gtk-4.0" }}'
  PKG_CONFIG_PATH: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "lib/pkgconfig" }}'
  XDG_DATA_DIRS: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "share" }}'

  GTK_DIR: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "" }}'
  GTK_PKG_CONFIG_DIR: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "lib/pkgconfig" }}'
  GTK_BIN_DIR: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "bin" }}'
  GTK_LIB_DIR: '{{ joinPath (.GVS_GTK_ROOT_DIR | default "") "lib" }}'

tasks:
  default:
    cmds:
      - task: build

  check-environment:
    aliases: [env]
    cmds:
      - cmd: | # shell
          PATH="$PATH_GTK" hb-info --help
      - cmd: | # shell
          for var in GTK_ROOT_DIR GTK_PKG_CONFIG_DIR GDK_PIXBUF_MODULE_FILE \
                     GIO_EXTRA_MODULES GTK_DATA_PREFIX \
                     GTK_LIB_DIR GTK_PATH PKG_CONFIG_PATH \
                     XDG_DATA_DIRS; do
            test -e "${!var}" && echo "✓ Path $var: '${!var}'" || echo "✗ Path $var: ${!var}"
          done

  sync:
    sources:
      - pyproject.toml
    generates:
      - .venv/**/*
    cmds:
      - cmd: uv sync

  build:
    deps: [gtk]
    sources:
      - ./Cargo.*
      - ./gtk4/**/*.rs
      - ./gtk4/**/Cargo.*
    generates:
      - ./target/release/gtk*{{exeExt}}
    cmds:
      - cmd: | # shell
          cmd.exe /D /C \
            rmdir /s /q "{{ joinPath .TASKFILE_DIR "target"}}" || true
      - cmd: | # shell
          cargo build --release --locked

  run:
    deps: [build]
    dir: ./target/release/
    cmds:
      - cmd: | # shell
          cargo run --release --locked

  gtk:
    deps: [gtk-build]
    vars:
      SOURCE_BIN_DIR: "{{.TASKFILE_DIR}}/{{.GVSBUILD_DIR_LNK}}/gtk/x64/release/bin"
      TARGET_BIN_DIR: "{{.TASKFILE_DIR}}/target/release"
    silent: true
    env:
      GTK_SOURCE_BIN_DIR: "{{.SOURCE_BIN_DIR | fromSlash}}"
      GTK_TARGET_BIN_DIR: "{{.TARGET_BIN_DIR | fromSlash}}"
    cmds:
      - cmd: | # shell
          if xcopy /y /s /i /d "$GTK_SOURCE_BIN_DIR" "$GTK_TARGET_BIN_DIR" >nul; then
            echo "Updated GTK binaries in target directory: '$GTK_TARGET_BIN_DIR'"
          else
            echo "Failed to copy GTK binaries to target directory."
            exit 1
          fi

  git-submodule-update:
    sources:
      - .gitmodules
    generates:
      - ./gir/.gitignore
      - ./gir-files/.gitignore
      - ./gtk/.gitignore
    cmds:
      - cmd: git submodule update --checkout --recursive

  gtk-build:
    deps: [git-submodule-update]
    aliases: [build-gtk, gtk4]
    sources:
      - uv.lock
    generates:
      - .build/gvsbuild/gtk/**/bin/gtk*.dll
    vars:
      DIR_LINK: "{{ joinPath .TASKFILE_DIR .GVSBUILD_DIR_LNK | fromSlash }}"
      DIR_TARGET: "{{.GVSBUILD_DIR | fromSlash}}"
    cmds:
      - cmd: | # shell
          {{.RUN}} mkdir "{{.DIR_LINK}}" || true
          {{.RUN}} rmdir /q /s "{{.DIR_LINK}}" || true
          {{.RUN}} mkdir "{{.DIR_TARGET}}" || true
          echo "Creating symlink {{.DIR_LINK}} -> {{.DIR_TARGET}}"
          {{.RUN}} mklink /D "{{.DIR_LINK}}" "{{.DIR_TARGET}}"
      - cmd: | # shell
          uv run gvsbuild \
            build gtk4 \
            {{if .VERBOSE}}--verbose{{end}} \
            --build-dir "{{.DIR_LINK}}" \
            --msys-dir "$USERPROFILE/scoop/apps/msys2/current"

  venv:
    sources:
      - pyproject.toml
    generates:
      - .venv/
    cmds:
      - cmd: uv sync

  install-dependencies:
    deps: [install-packages-scoop-pkg-config]
    cmds:
      - task: install-packages

  scoop-install:
    desc: Install libraries with scoop
    status:
      - "scoop --version"
    cmds:
      - cmd: | # shell
          pwsh -NoProfile -Command 'iex "& {$(irm get.scoop.sh)} -RunAsAdmin"'
        platforms: [windows]
        ignore_error: true
      - cmd: pwsh -NoProfile -Command 'Join-Path (Resolve-Path ~).Path "scoop/shims" >> $Env:GITHUB_PATH'
        platforms: [windows]
        ignore_error: true

  update-packages:
    ignore_error: true
    cmds:
      - task: update-packages-pacman

  update-packages-pacman:
    deps: [pacman-unlock]
    cmds:
      - task: pacman-unlock
      - cmd: "pacman -Syu --noconfirm"
        ignore_error: true

  install-packages:
    cmds:
      - task: install-packages-scoop-pkg-config
      - task: install-packages-pacman

  install-packages-scoop-pkg-config:
    deps: [scoop-install]
    platforms: [windows]
    status:
      - pkg-config --version
    cmds:
      - cmd: |
          scoop install \
            extras/pkg-config-lite \
            main/winflexbison

  install-packages-pacman:
    vars:
      PACKAGES: '{{.MSYS2_PACKAGES | join " "}}'
    cmds:
      - task: pacman-unlock
      - cmd: "pacman -Syu --noconfirm"
        ignore_error: true
      - cmd: "pacman -S --needed --noconfirm {{ .PACKAGES }}"
        ignore_error: true
      - task: pacman-unlock

  install-each-package:
    deps: [update-packages]
    vars:
      PACKAGES: '{{.MSYS2_PACKAGES | join " "}}'
    cmds:
      - for:
          var: MSYS2_PACKAGES
        task: install-package-pacman
        vars:
          PACKAGE: "{{.ITEM}}"

  pacman-unlock:
    status:
      - "test ! -f /var/lib/pacman/db.lck"
    cmds:
      - cmd: "rm -f /var/lib/pacman/db.lck"
        ignore_error: true

  install-package-pacman:
    deps: [pacman-unlock]
    requires:
      vars: [PACKAGE]
    desc: "Install package {{.PACKAGE}}"
    preconditions:
      - "pacman --version"
    status:
      - "pacman -Qk {{.PACKAGE}}"
    cmds:
      - cmd: 'pacman -S --needed --noconfirm "{{.PACKAGE}}"'

  delete:
    internal: true
    requires: { vars: [TARGET_DIR] }
    status:
      - 'test ! -d "{{.TARGET_DIR}}"'
    cmds:
      - cmd: '{{.RUN}} if exist "{{.TARGET_DIR}}" rmdir /s /q "{{.TARGET_DIR}}"'
        platforms: [windows]
      - cmd: '{{.RUN}} rm -rf "{{.TARGET_DIR}}"'
        platforms: [linux, darwin]
